/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperadminPlansRouteImport } from './routes/superadmin.plans'
import { Route as SuperadminBillingRouteImport } from './routes/superadmin.billing'
import { Route as EmployeeSurveysRouteImport } from './routes/employee.surveys'
import { Route as EmployeeMessagesRouteImport } from './routes/employee.messages'
import { Route as EmployeeLibraryRouteImport } from './routes/employee.library'
import { Route as EmployeeHomeRouteImport } from './routes/employee.home'
import { Route as EmployeeHelpRouteImport } from './routes/employee.help'
import { Route as EmployeeFeedbackRouteImport } from './routes/employee.feedback'
import { Route as EmployeeEventsRouteImport } from './routes/employee.events'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSurveysRouteImport } from './routes/admin.surveys'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminErpRouteImport } from './routes/admin.erp'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBurnoutRouteImport } from './routes/admin.burnout'
import { Route as AdminAnonymousRouteImport } from './routes/admin.anonymous'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AdminActionsRouteImport } from './routes/admin.actions'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperadminPlansRoute = SuperadminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminBillingRoute = SuperadminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SuperadminRoute,
} as any)
const EmployeeSurveysRoute = EmployeeSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeMessagesRoute = EmployeeMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeLibraryRoute = EmployeeLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeHomeRoute = EmployeeHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeHelpRoute = EmployeeHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeFeedbackRoute = EmployeeFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeEventsRoute = EmployeeEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => EmployeeRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveysRoute = AdminSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminErpRoute = AdminErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBurnoutRoute = AdminBurnoutRouteImport.update({
  id: '/burnout',
  path: '/burnout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnonymousRoute = AdminAnonymousRouteImport.update({
  id: '/anonymous',
  path: '/anonymous',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActionsRoute = AdminActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/actions': typeof AdminActionsRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/anonymous': typeof AdminAnonymousRoute
  '/admin/burnout': typeof AdminBurnoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/erp': typeof AdminErpRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/surveys': typeof AdminSurveysRoute
  '/admin/team': typeof AdminTeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/employee/events': typeof EmployeeEventsRoute
  '/employee/feedback': typeof EmployeeFeedbackRoute
  '/employee/help': typeof EmployeeHelpRoute
  '/employee/home': typeof EmployeeHomeRoute
  '/employee/library': typeof EmployeeLibraryRoute
  '/employee/messages': typeof EmployeeMessagesRoute
  '/employee/surveys': typeof EmployeeSurveysRoute
  '/superadmin/billing': typeof SuperadminBillingRoute
  '/superadmin/plans': typeof SuperadminPlansRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/anonymous': typeof AdminAnonymousRoute
  '/admin/burnout': typeof AdminBurnoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/erp': typeof AdminErpRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/surveys': typeof AdminSurveysRoute
  '/admin/team': typeof AdminTeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/employee/events': typeof EmployeeEventsRoute
  '/employee/feedback': typeof EmployeeFeedbackRoute
  '/employee/help': typeof EmployeeHelpRoute
  '/employee/home': typeof EmployeeHomeRoute
  '/employee/library': typeof EmployeeLibraryRoute
  '/employee/messages': typeof EmployeeMessagesRoute
  '/employee/surveys': typeof EmployeeSurveysRoute
  '/superadmin/billing': typeof SuperadminBillingRoute
  '/superadmin/plans': typeof SuperadminPlansRoute
  '/admin': typeof AdminIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/actions': typeof AdminActionsRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/anonymous': typeof AdminAnonymousRoute
  '/admin/burnout': typeof AdminBurnoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/erp': typeof AdminErpRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/surveys': typeof AdminSurveysRoute
  '/admin/team': typeof AdminTeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/employee/events': typeof EmployeeEventsRoute
  '/employee/feedback': typeof EmployeeFeedbackRoute
  '/employee/help': typeof EmployeeHelpRoute
  '/employee/home': typeof EmployeeHomeRoute
  '/employee/library': typeof EmployeeLibraryRoute
  '/employee/messages': typeof EmployeeMessagesRoute
  '/employee/surveys': typeof EmployeeSurveysRoute
  '/superadmin/billing': typeof SuperadminBillingRoute
  '/superadmin/plans': typeof SuperadminPlansRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/employee'
    | '/onboarding'
    | '/superadmin'
    | '/admin/actions'
    | '/admin/alerts'
    | '/admin/anonymous'
    | '/admin/burnout'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/erp'
    | '/admin/events'
    | '/admin/library'
    | '/admin/messages'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/surveys'
    | '/admin/team'
    | '/auth/callback'
    | '/employee/events'
    | '/employee/feedback'
    | '/employee/help'
    | '/employee/home'
    | '/employee/library'
    | '/employee/messages'
    | '/employee/surveys'
    | '/superadmin/billing'
    | '/superadmin/plans'
    | '/admin/'
    | '/employee/'
    | '/superadmin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/auth'
    | '/checkout'
    | '/onboarding'
    | '/admin/actions'
    | '/admin/alerts'
    | '/admin/anonymous'
    | '/admin/burnout'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/erp'
    | '/admin/events'
    | '/admin/library'
    | '/admin/messages'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/surveys'
    | '/admin/team'
    | '/auth/callback'
    | '/employee/events'
    | '/employee/feedback'
    | '/employee/help'
    | '/employee/home'
    | '/employee/library'
    | '/employee/messages'
    | '/employee/surveys'
    | '/superadmin/billing'
    | '/superadmin/plans'
    | '/admin'
    | '/employee'
    | '/superadmin'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/employee'
    | '/onboarding'
    | '/superadmin'
    | '/admin/actions'
    | '/admin/alerts'
    | '/admin/anonymous'
    | '/admin/burnout'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/erp'
    | '/admin/events'
    | '/admin/library'
    | '/admin/messages'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/surveys'
    | '/admin/team'
    | '/auth/callback'
    | '/employee/events'
    | '/employee/feedback'
    | '/employee/help'
    | '/employee/home'
    | '/employee/library'
    | '/employee/messages'
    | '/employee/surveys'
    | '/superadmin/billing'
    | '/superadmin/plans'
    | '/admin/'
    | '/employee/'
    | '/superadmin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  EmployeeRoute: typeof EmployeeRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/superadmin/plans': {
      id: '/superadmin/plans'
      path: '/plans'
      fullPath: '/superadmin/plans'
      preLoaderRoute: typeof SuperadminPlansRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/billing': {
      id: '/superadmin/billing'
      path: '/billing'
      fullPath: '/superadmin/billing'
      preLoaderRoute: typeof SuperadminBillingRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/employee/surveys': {
      id: '/employee/surveys'
      path: '/surveys'
      fullPath: '/employee/surveys'
      preLoaderRoute: typeof EmployeeSurveysRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/messages': {
      id: '/employee/messages'
      path: '/messages'
      fullPath: '/employee/messages'
      preLoaderRoute: typeof EmployeeMessagesRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/library': {
      id: '/employee/library'
      path: '/library'
      fullPath: '/employee/library'
      preLoaderRoute: typeof EmployeeLibraryRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/home': {
      id: '/employee/home'
      path: '/home'
      fullPath: '/employee/home'
      preLoaderRoute: typeof EmployeeHomeRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/help': {
      id: '/employee/help'
      path: '/help'
      fullPath: '/employee/help'
      preLoaderRoute: typeof EmployeeHelpRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/feedback': {
      id: '/employee/feedback'
      path: '/feedback'
      fullPath: '/employee/feedback'
      preLoaderRoute: typeof EmployeeFeedbackRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/events': {
      id: '/employee/events'
      path: '/events'
      fullPath: '/employee/events'
      preLoaderRoute: typeof EmployeeEventsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys': {
      id: '/admin/surveys'
      path: '/surveys'
      fullPath: '/admin/surveys'
      preLoaderRoute: typeof AdminSurveysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/erp': {
      id: '/admin/erp'
      path: '/erp'
      fullPath: '/admin/erp'
      preLoaderRoute: typeof AdminErpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/burnout': {
      id: '/admin/burnout'
      path: '/burnout'
      fullPath: '/admin/burnout'
      preLoaderRoute: typeof AdminBurnoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anonymous': {
      id: '/admin/anonymous'
      path: '/anonymous'
      fullPath: '/admin/anonymous'
      preLoaderRoute: typeof AdminAnonymousRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/actions': {
      id: '/admin/actions'
      path: '/actions'
      fullPath: '/admin/actions'
      preLoaderRoute: typeof AdminActionsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActionsRoute: typeof AdminActionsRoute
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminAnonymousRoute: typeof AdminAnonymousRoute
  AdminBurnoutRoute: typeof AdminBurnoutRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminErpRoute: typeof AdminErpRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSurveysRoute: typeof AdminSurveysRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActionsRoute: AdminActionsRoute,
  AdminAlertsRoute: AdminAlertsRoute,
  AdminAnonymousRoute: AdminAnonymousRoute,
  AdminBurnoutRoute: AdminBurnoutRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminErpRoute: AdminErpRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSurveysRoute: AdminSurveysRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface EmployeeRouteChildren {
  EmployeeEventsRoute: typeof EmployeeEventsRoute
  EmployeeFeedbackRoute: typeof EmployeeFeedbackRoute
  EmployeeHelpRoute: typeof EmployeeHelpRoute
  EmployeeHomeRoute: typeof EmployeeHomeRoute
  EmployeeLibraryRoute: typeof EmployeeLibraryRoute
  EmployeeMessagesRoute: typeof EmployeeMessagesRoute
  EmployeeSurveysRoute: typeof EmployeeSurveysRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeEventsRoute: EmployeeEventsRoute,
  EmployeeFeedbackRoute: EmployeeFeedbackRoute,
  EmployeeHelpRoute: EmployeeHelpRoute,
  EmployeeHomeRoute: EmployeeHomeRoute,
  EmployeeLibraryRoute: EmployeeLibraryRoute,
  EmployeeMessagesRoute: EmployeeMessagesRoute,
  EmployeeSurveysRoute: EmployeeSurveysRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

interface SuperadminRouteChildren {
  SuperadminBillingRoute: typeof SuperadminBillingRoute
  SuperadminPlansRoute: typeof SuperadminPlansRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminBillingRoute: SuperadminBillingRoute,
  SuperadminPlansRoute: SuperadminPlansRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  EmployeeRoute: EmployeeRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
